services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    restart: unless-stopped

  redis:
    image: redis:latest
    restart: unless-stopped

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    restart: unless-stopped
